Create ru_ru.json
isXander/Debugify pull request #196
Opened 2023-01-03 01:18 UTC by FurnyGo

2023-01-23 11:33 UTC, imDaniX requested changes

2023-01-23 11:33 UTC, imDaniX commented on src/main/resources/assets/debugify/lang/ru_ru.json
> +  "debugify.gameplay.warning": "ВНИМАНИЕ: Эта категория содержит исправления, которые могут быть несправедливым преимуществом!",
Стоит изменить на "могут являться". Окончание на "несправедливым приемуществом" кажется немного неприятным на слух, будто что-то дальше должно идти, но вряд ли можно что-то сделать так просто.

2023-01-23 11:33 UTC, imDaniX commented on src/main/resources/assets/debugify/lang/ru_ru.json
> +  "debugify.misc.default_disabled": "По умолчанию отключено",
"Default" здесь глагол. Правильнее и менее странно на слух будет "Отключать по умолчанию"

2023-01-23 11:33 UTC, imDaniX commented on src/main/resources/assets/debugify/lang/ru_ru.json
> +  "debugify.misc.default_disabled.description": "По умолчанию новые исправления ошибок будут отключены, а не включены.",
Прямой перевод не очень хорошо работает. Скорей что-то вроде "Все новые исправления будут по умолчанию отключены.", или хотя бы убрать "а не включены".

2023-01-23 11:33 UTC, imDaniX commented on src/main/resources/assets/debugify/lang/ru_ru.json
> +  "debugify.env.client.desc": "Исправления, которые применяются только к клиенту.",
Мелочь, но хотелось бы с `debugify.env.server.desc` соответствие. "Исправления, применимые..."

2023-01-23 11:33 UTC, imDaniX commented on src/main/resources/assets/debugify/lang/ru_ru.json
> +  "debugify.no_yacl.description": "Чтобы настроить Debugify с помощью графического интерфейса, вы должны установить %s, это библиотека, используемая для предоставления этой функции. Вы можете настрои
"это", "этой" - несколько неправильно в одном предложении, а ещё перед "это" требуется тире. Во втором предложении опущено "Otherwise".
Может что-то вроде "Для настройки Debugify через графический интерфейс требуется мод %s - это библиотека, используемая для предоставленияя данной функции. Иначе вы можете отредактировать настройки мода в JSON файле, хранящемся по пути '%s'."

2023-01-23 11:33 UTC, imDaniX commented on src/main/resources/assets/debugify/lang/ru_ru.json
> +  "debugify.mc_237493.line": "Вы выбрали '%s' в параметре телеметрии, поэтому Debugify предотвращает любое подключение к службам телеметрии из Mojang. Это предусмотрено Debugify для исправления MC-23
Стоит опустить "из" перед "Mojang". "telemetry services from Mojang" предполагает, что это их сервисы, а не какие-то выходящие из них.

2023-01-31 14:05 UTC, imDaniX approved these changes

2023-03-10 08:37 UTC, Felix14-v2 requested changes
Н̶е̶большое замечание — апостроф **не используется** в русском языке в качестве кавычек, только для обозначения иностранных имён или фамилий (иногда в виде разделения непереводимых слов — Microsoft'ы), вместо этого возможно использование двойных кавычек `"` или кавычек-ёлочек `«»`. В официальной локализации Minecraft используются именно последние, поэтому все апострофы необходимо заменить на них.

2023-03-10 08:45 UTC, Felix14-v2 commented on src/main/resources/assets/debugify/lang/ru_ru.json
> +  "debugify.mc_237493.tooltip.minimal": "'%s' включает только ту информацию, которую Mojang сочтет необходимой.",
Также, хотя правила русского языка в данном случае к этому не обязывают, было бы приятно всё же видеть букву `ё` на её законном месте :)
```suggestion
  "debugify.mc_237493.tooltip.minimal": "«%s» включает только ту информацию, которую Mojang сочтёт необходимой.",
```

2023-04-16 17:00 UTC, merged