Fix MC-8187
isXander/Debugify pull request #259
Opened 2023-06-19 08:47 UTC by Ampflower

Mixin code provided nearly as is from https://github.com/Modflower/8187

The test suite was made to strictly test the saplings. Note that the test suite only tests growing on NW as it isn't necessary to test the other 3 corners, despite being easy to fit in by the architecture of the code.

2023-06-20 09:16 UTC, isXander requested changes
Overall great! Thank you very much for your contribution. Just a few little changes!

2023-06-20 09:16 UTC, isXander commented on src/main/java/dev/isxander/debugify/mixins/gameplay/mc8187/MixinTreeFeature.java
> +	@ModifyVariable(method = "getMaxFreeTreeHeight", at = @At(value = "STORE", ordinal = 0), allow = 1, index = 8)
Could you use a @Slice for this to not use such a high index?
Also, please use ordinal over index. This goes for the other mixin as well.

2023-06-20 09:16 UTC, isXander commented on src/main/java/dev/isxander/debugify/mixins/gameplay/mc8187/MixinTreeFeature.java
> +		return flwr8187$fixOffset(v, world, i, pos, config);
Rather than calling the other mixin, could you make it another method that both mixins call?

2023-06-20 09:16 UTC, isXander commented on src/main/java/dev/isxander/debugify/mixins/gameplay/mc8187/MixinTreeFeature.java
> +	private int flwr8187$fixOffset(int startValue, LevelSimulatedReader world, int i, BlockPos pos, TreeConfiguration config) {
No need to prefix mixin methods. It is done automatically by mixin and doesn't match all other Debugify mixins. Maybe a slightly more descriptive name?

2023-06-20 09:16 UTC, isXander commented on src/gametest/java/dev/isxander/debugify/test/DebugifyMc8187TestSuite.java
> +public class DebugifyMc8187TestSuite implements FabricGameTest {
If you are making a dedicated test suite for this, could you separate the other test suite into their own fixes like yours?

2023-06-20 09:16 UTC, isXander commented on src/gametest/java/dev/isxander/debugify/test/DebugifyTestUtilites.java
> +public final class DebugifyTestUtilites {
Why `Utilities`? Could you shorten this to `Utils`?

2023-06-20 23:29 UTC, Ampflower commented on src/gametest/java/dev/isxander/debugify/test/DebugifyMc8187TestSuite.java
> +public class DebugifyMc8187TestSuite implements FabricGameTest {
Sure. I mainly did that for MC-8187 since it did a lot more tests, and it seemed like it'd be cleaner to have it have its own for easily removing it in the future.

2023-06-20 23:29 UTC, Ampflower commented on src/gametest/java/dev/isxander/debugify/test/DebugifyTestUtilites.java
> +public final class DebugifyTestUtilites {
Not sure why I went Utilities instead of Utils, tho I'll rename.

2023-06-20 23:32 UTC, Ampflower commented on src/main/java/dev/isxander/debugify/mixins/gameplay/mc8187/MixinTreeFeature.java
> +	private int flwr8187$fixOffset(int startValue, LevelSimulatedReader world, int i, BlockPos pos, TreeConfiguration config) {
You know, I didn't think to rename the prefix at least.

Would debugify$ work, or should I just omit it entirely?

I originally added it there mainly because Mixin doesn't actually prefix the mod ID, only a hash that's not really useful for finding who threw the exception without using `-Dmixin.export=true`.

2023-06-20 23:42 UTC, Ampflower commented on src/gametest/java/dev/isxander/debugify/test/DebugifyMc8187TestSuite.java
> +public class DebugifyMc8187TestSuite implements FabricGameTest {
Curious, should I make a suites package of some sort to separate the utils from the actual tests?

2023-06-21 00:02 UTC, Ampflower commented on src/main/java/dev/isxander/debugify/mixins/gameplay/mc8187/MixinTreeFeature.java
> +	@ModifyVariable(method = "getMaxFreeTreeHeight", at = @At(value = "STORE", ordinal = 0), allow = 1, index = 8)
`@Slice` doesn't seem to change much for index and ordinal, tho I suppose it does make it stricter if Mojang ever changes this method later.

2023-06-21 00:06 UTC, Ampflower commented
Implemented changes requested and marked those without any questions or potential insight as resolved.

2023-06-21 20:48 UTC, isXander commented on src/main/java/dev/isxander/debugify/mixins/gameplay/mc8187/MixinTreeFeature.java
> +	@ModifyVariable(method = "getMaxFreeTreeHeight", at = @At(value = "STORE", ordinal = 0), allow = 1, index = 8)
At least use ordinal then.

2023-06-21 20:49 UTC, isXander commented on src/main/java/dev/isxander/debugify/mixins/gameplay/mc8187/MixinTreeFeature.java
> +	private int flwr8187$fixOffset(int startValue, LevelSimulatedReader world, int i, BlockPos pos, TreeConfiguration config) {
Just remove entirely. Debugify already catches it.

2023-06-21 20:49 UTC, isXander commented on src/gametest/java/dev/isxander/debugify/test/DebugifyMc8187TestSuite.java
> +public class DebugifyMc8187TestSuite implements FabricGameTest {
Not sure what you mean.

2023-06-22 02:09 UTC, Ampflower commented on src/gametest/java/dev/isxander/debugify/test/DebugifyMc8187TestSuite.java
> +public class DebugifyMc8187TestSuite implements FabricGameTest {
Like all the tests will go into its own package nested down, so it's easy to tell which are the utilities and the actual tests at a glance.

So, like:
...debugify.tests
 - TestUtils
 - ApiTest
 - suites
   - Mc8187
   - Mc...

2023-06-28 22:17 UTC, isXander approved these changes

2023-06-28 22:22 UTC, merged